team:
  name: CodeClouders
  members:
    - user: ja.romerog12@uniandes.edu.co
      percentage: 25
    - user: lj.torresm1@uniandes.edu.co
      percentage: 25
    - user: v.castanedap@uniandes.edu.co
      percentage: 25
    - user: k.maldonadod@uniandes.edu.co
      percentage: 25
board: https://github.com/orgs/MISW-4301-Desarrollo-Apps-en-la-Nube/projects/129
url: 34.49.37.86
user-management:
  folder: msusers
  port: 3000
  authors:
    - ja.romerog12@uniandes.edu.co
post-management:
  folder: posts
  port: 3001
  authors:
    - v.castanedap@uniandes.edu.co
offer-management:
  folder: offers
  port: 3003
  authors:
    - lj.torresm1@uniandes.edu.co
route-management:
  folder: route
  port: 3002
  authors:
    - k.maldonadod@uniandes.edu.co
rf003-management:
  folder: rf003
  port: 3006
  authors:
    - k.maldonadod@uniandes.edu.co
rf004-management:
  folder: rf04
  port: 3004
  authors:
    - ja.romerog12@uniandes.edu.co
rf005-management:
  folder: rf005
  port: 3005
  authors:
    - lj.torresm1@uniandes.edu.co
scores-management:
  folder: score
  port: 3008
  authors:
    - v.castanedap@uniandes.edu.co