apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "postgresql"
  DB_HOST: "130.211.204.96"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  USERS_PATH: "http://users"
apiVersion: v1
kind: Secret
metadata:
  name: rf003-secrets
type: Opaque
stringData:
  BASE_URL_ROUTE: "http://routes-kubernates-service"
  BASE_URL_POST: "http://posts-kubernates-service"
apiVersion: v1
kind: Secret
metadata:
  name: rf004-secrets
type: Opaque
stringData:
  POSTS_PATH: "http://posts-kubernates-service"
  USERS_PATH: "http://users"
  OFFERS_PATH: "http://offers-kubernates-service"
apiVersion: v1
kind: Secret
metadata:
  name: rf005-secrets
type: Opaque
stringData:
  POSTS_PATH: "http://posts-kubernates-service"
  USERS_PATH: "http://users"
  OFFERS_PATH: "http://offers-kubernates-service"
  ROUTES_PATH: "http://routes-kubernates-service"
  SCORE_PATH: "http://scores-kubernates-service"