version: "3.8"
   
services:  
  offers:
    build: .
    ports:
      - "3003:3003"
    environment:
      DB_NAME: monitor_offers
      DB_HOST: offers_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      USERS_PATH: "http://users:3000"
    depends_on:
      offers_db:
        condition: service_healthy
    #networks:
    #  - offer_net
    #  - app_net
  offers_db:
    image: postgres
    environment:
      POSTGRES_DB: monitor_offers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
    #networks:
    #  - offer_net
  #networks:
  #offer_net:
  #app_net:
   